// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxlehvwvagojxpbosvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeGxlaHZ3dmFnb2p4cGJvc3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTQ4NDksImV4cCI6MjA1NzU5MDg0OX0.0fgTv9_XYNOBfcgYCxYYuEUiEcFiJKEGivHExIou_rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);